# Generated by Django 5.1.4 on 2025-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_created_at_category_updated_at_and_more'),
        ('job', '0002_jobpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='category.skills'),
        ),
    ]
